version: '3'

services:
    #api
    api:
      build:
        context: .
        args:
          - WORKSPACE=${WORKSPACE}
      restart: always
      volumes:
        - ${DATA_PATH_HOST}/api/${APP_NAME}/upload:/api/upload
        - ${DATA_PATH_HOST}/api/${APP_NAME}/log:/api/log
      command: bash -c "go install &&
                        ${APP_NAME} http"
      networks:
        - backend
networks:
  backend:
    external: true