version: '3'
services: 
    #web
    api:
        container_name: api
        build:
            context: .
            args: 
                - WORKDIR=api
        ports:
            - ${APP_PORT}:${APP_PORT}
        volumes: 
            - ${DATA_PATH_HOST}/api/${APP_NAME}/upload:/api/${APP_NAME}/upload
        environment: 
            - APP_NAME=${APP_NAME}
            - APP_ENV=${APP_ENV}
            - JWT_SECRET=${JWT_SECRET}
        links:
            - mysql
    #mysql
    mysql:
        container_name: mysql
        build: ./docker/mysql
        ports:
            - ${DB_PORT}:${DB_PORT}
        volumes: 
            - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
            - ./docker/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
        environment: 
            - MYSQL_VERSION=${MYSQL_VERSION}
            - MYSQL_DATABASE=${APP_NAME}
            - MYSQL_USER=${APP_NAME}
            - MYSQL_PASSWORD=${APP_NAME}
            - MYSQL_PORT=${MYSQL_PORT}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_ENTRYPOINT_INITDB=${MYSQL_ENTRYPOINT_INITDB}
            - TZ=${TZ}
    #adminer
    adminer:
        container_name: adminer
        build: ./docker/adminer
        ports:
            - ${ADMIMER_PORT}:${ADMIMER_PORT}
        environment: 
            - ADMINER_DEFAULT_SERVER=${ADMINER_DEFAULT_SERVER}
    #minio
    minio:
        container_name: minio
        build: ./docker/minio
        volumes:
          - ${DATA_PATH_HOST}/minio:/data
        #   - ${CONFIG_PATH_HOST}/minio:/root/.minio
        ports:
          - "9000:9000"
        environment:
          - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
          - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
        command: server /data
        healthcheck:
          test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
          interval: 30s
          timeout: 20s
          retries: 3
    #phpmyadmin
    # phpmyadmin:
    #     build: ./docker/phpmyadmin
    #     ports: 
    #         - ${PMA_PORT}:80
    #     env_file:
    #         ./docker/phpmyadmin/.env
    #     depends_on: 
    #         - mysql
            

        