version: '3'

services:
    #api
    api:
      build:
        context: .
        dockerfile: ./docker/api/Dockerfile
        args:
          - WORKSPACE=api
      restart: always
      volumes:
        - ${DATA_PATH_HOST}/api/${APP_NAME}/upload:/api/upload
        - ${DATA_PATH_HOST}/api/${APP_NAME}/log:/api/log
      networks:
        - backend

    #socketio
    socketio:
      build:
        context: .
        dockerfile: ./docker/socketio/Dockerfile
        args:
          - WORKSPACE=socketio
      restart: always
      volumes:
        - ${DATA_PATH_HOST}/socketio/${APP_NAME}/upload:/socketio/upload
        - ${DATA_PATH_HOST}/socketio/${APP_NAME}/log:/socketio/log
      networks:
        - backend
networks:
  backend:
    external: true