FROM golang:alpine AS builder
WORKDIR /app
COPY . /app
RUN GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -ldflags="-w -s" main.go

FROM alpine:latest AS runner
WORKDIR /app
COPY --from=builder /app/main .
# timezone
RUN apk add --no-cache tzdata
ENV TZ $TZ
EXPOSE 80
CMD ["./main", "http"]
