// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: games.proto

package games

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GreeterClient is the client API for Greeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GreeterClient interface {
	RandomTicket(ctx context.Context, in *RandomTicketRequest, opts ...grpc.CallOption) (*RandomTicketResponse, error)
	AssignRandomIssuedTicketToThirdPartyUser(ctx context.Context, in *AssignRandomIssuedTicketToThirdPartyUserRequest, opts ...grpc.CallOption) (*AssignRandomIssuedTicketToThirdPartyUserResponse, error)
}

type greeterClient struct {
	cc grpc.ClientConnInterface
}

func NewGreeterClient(cc grpc.ClientConnInterface) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) RandomTicket(ctx context.Context, in *RandomTicketRequest, opts ...grpc.CallOption) (*RandomTicketResponse, error) {
	out := new(RandomTicketResponse)
	err := c.cc.Invoke(ctx, "/games.Greeter/RandomTicket", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) AssignRandomIssuedTicketToThirdPartyUser(ctx context.Context, in *AssignRandomIssuedTicketToThirdPartyUserRequest, opts ...grpc.CallOption) (*AssignRandomIssuedTicketToThirdPartyUserResponse, error) {
	out := new(AssignRandomIssuedTicketToThirdPartyUserResponse)
	err := c.cc.Invoke(ctx, "/games.Greeter/AssignRandomIssuedTicketToThirdPartyUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreeterServer is the server API for Greeter service.
// All implementations must embed UnimplementedGreeterServer
// for forward compatibility
type GreeterServer interface {
	RandomTicket(context.Context, *RandomTicketRequest) (*RandomTicketResponse, error)
	AssignRandomIssuedTicketToThirdPartyUser(context.Context, *AssignRandomIssuedTicketToThirdPartyUserRequest) (*AssignRandomIssuedTicketToThirdPartyUserResponse, error)
	mustEmbedUnimplementedGreeterServer()
}

// UnimplementedGreeterServer must be embedded to have forward compatible implementations.
type UnimplementedGreeterServer struct {
}

func (UnimplementedGreeterServer) RandomTicket(context.Context, *RandomTicketRequest) (*RandomTicketResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RandomTicket not implemented")
}
func (UnimplementedGreeterServer) AssignRandomIssuedTicketToThirdPartyUser(context.Context, *AssignRandomIssuedTicketToThirdPartyUserRequest) (*AssignRandomIssuedTicketToThirdPartyUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AssignRandomIssuedTicketToThirdPartyUser not implemented")
}
func (UnimplementedGreeterServer) mustEmbedUnimplementedGreeterServer() {}

// UnsafeGreeterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GreeterServer will
// result in compilation errors.
type UnsafeGreeterServer interface {
	mustEmbedUnimplementedGreeterServer()
}

func RegisterGreeterServer(s grpc.ServiceRegistrar, srv GreeterServer) {
	s.RegisterService(&Greeter_ServiceDesc, srv)
}

func _Greeter_RandomTicket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RandomTicketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).RandomTicket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/games.Greeter/RandomTicket",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).RandomTicket(ctx, req.(*RandomTicketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_AssignRandomIssuedTicketToThirdPartyUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignRandomIssuedTicketToThirdPartyUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).AssignRandomIssuedTicketToThirdPartyUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/games.Greeter/AssignRandomIssuedTicketToThirdPartyUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).AssignRandomIssuedTicketToThirdPartyUser(ctx, req.(*AssignRandomIssuedTicketToThirdPartyUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Greeter_ServiceDesc is the grpc.ServiceDesc for Greeter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Greeter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "games.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RandomTicket",
			Handler:    _Greeter_RandomTicket_Handler,
		},
		{
			MethodName: "AssignRandomIssuedTicketToThirdPartyUser",
			Handler:    _Greeter_AssignRandomIssuedTicketToThirdPartyUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "games.proto",
}
