// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.12.4
// source: games.proto

package games

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RandomTicketRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count int64 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *RandomTicketRequest) Reset() {
	*x = RandomTicketRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_games_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RandomTicketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RandomTicketRequest) ProtoMessage() {}

func (x *RandomTicketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_games_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RandomTicketRequest.ProtoReflect.Descriptor instead.
func (*RandomTicketRequest) Descriptor() ([]byte, []int) {
	return file_games_proto_rawDescGZIP(), []int{0}
}

func (x *RandomTicketRequest) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type RandomTicketResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *RandomTicketResponse) Reset() {
	*x = RandomTicketResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_games_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RandomTicketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RandomTicketResponse) ProtoMessage() {}

func (x *RandomTicketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_games_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RandomTicketResponse.ProtoReflect.Descriptor instead.
func (*RandomTicketResponse) Descriptor() ([]byte, []int) {
	return file_games_proto_rawDescGZIP(), []int{1}
}

func (x *RandomTicketResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AssignRandomIssuedTicketToThirdPartyUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code         string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	ThirdPartyID string `protobuf:"bytes,2,opt,name=thirdPartyID,proto3" json:"thirdPartyID,omitempty"`
}

func (x *AssignRandomIssuedTicketToThirdPartyUserRequest) Reset() {
	*x = AssignRandomIssuedTicketToThirdPartyUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_games_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AssignRandomIssuedTicketToThirdPartyUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignRandomIssuedTicketToThirdPartyUserRequest) ProtoMessage() {}

func (x *AssignRandomIssuedTicketToThirdPartyUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_games_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignRandomIssuedTicketToThirdPartyUserRequest.ProtoReflect.Descriptor instead.
func (*AssignRandomIssuedTicketToThirdPartyUserRequest) Descriptor() ([]byte, []int) {
	return file_games_proto_rawDescGZIP(), []int{2}
}

func (x *AssignRandomIssuedTicketToThirdPartyUserRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *AssignRandomIssuedTicketToThirdPartyUserRequest) GetThirdPartyID() string {
	if x != nil {
		return x.ThirdPartyID
	}
	return ""
}

type AssignRandomIssuedTicketToThirdPartyUserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Code string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *AssignRandomIssuedTicketToThirdPartyUserResponse) Reset() {
	*x = AssignRandomIssuedTicketToThirdPartyUserResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_games_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AssignRandomIssuedTicketToThirdPartyUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignRandomIssuedTicketToThirdPartyUserResponse) ProtoMessage() {}

func (x *AssignRandomIssuedTicketToThirdPartyUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_games_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignRandomIssuedTicketToThirdPartyUserResponse.ProtoReflect.Descriptor instead.
func (*AssignRandomIssuedTicketToThirdPartyUserResponse) Descriptor() ([]byte, []int) {
	return file_games_proto_rawDescGZIP(), []int{3}
}

func (x *AssignRandomIssuedTicketToThirdPartyUserResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AssignRandomIssuedTicketToThirdPartyUserResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

var File_games_proto protoreflect.FileDescriptor

var file_games_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x67, 0x61, 0x6d, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x67,
	0x61, 0x6d, 0x65, 0x73, 0x22, 0x2b, 0x0a, 0x13, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x54, 0x69,
	0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x22, 0x30, 0x0a, 0x14, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x54, 0x69, 0x63, 0x6b, 0x65,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x22, 0x69, 0x0a, 0x2f, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x52, 0x61, 0x6e,
	0x64, 0x6f, 0x6d, 0x49, 0x73, 0x73, 0x75, 0x65, 0x64, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x54,
	0x6f, 0x54, 0x68, 0x69, 0x72, 0x64, 0x50, 0x61, 0x72, 0x74, 0x79, 0x55, 0x73, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x74, 0x68,
	0x69, 0x72, 0x64, 0x50, 0x61, 0x72, 0x74, 0x79, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x74, 0x68, 0x69, 0x72, 0x64, 0x50, 0x61, 0x72, 0x74, 0x79, 0x49, 0x44, 0x22, 0x5a,
	0x0a, 0x30, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x49, 0x73,
	0x73, 0x75, 0x65, 0x64, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x54, 0x6f, 0x54, 0x68, 0x69, 0x72,
	0x64, 0x50, 0x61, 0x72, 0x74, 0x79, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x32, 0xf4, 0x01, 0x0a, 0x07, 0x47,
	0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x12, 0x49, 0x0a, 0x0c, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d,
	0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x1a, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x73, 0x2e, 0x52,
	0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x73, 0x2e, 0x52, 0x61, 0x6e, 0x64, 0x6f,
	0x6d, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x9d, 0x01, 0x0a, 0x28, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x52, 0x61, 0x6e, 0x64,
	0x6f, 0x6d, 0x49, 0x73, 0x73, 0x75, 0x65, 0x64, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x54, 0x6f,
	0x54, 0x68, 0x69, 0x72, 0x64, 0x50, 0x61, 0x72, 0x74, 0x79, 0x55, 0x73, 0x65, 0x72, 0x12, 0x36,
	0x2e, 0x67, 0x61, 0x6d, 0x65, 0x73, 0x2e, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x52, 0x61, 0x6e,
	0x64, 0x6f, 0x6d, 0x49, 0x73, 0x73, 0x75, 0x65, 0x64, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x54,
	0x6f, 0x54, 0x68, 0x69, 0x72, 0x64, 0x50, 0x61, 0x72, 0x74, 0x79, 0x55, 0x73, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x37, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x73, 0x2e, 0x41,
	0x73, 0x73, 0x69, 0x67, 0x6e, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x49, 0x73, 0x73, 0x75, 0x65,
	0x64, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x54, 0x6f, 0x54, 0x68, 0x69, 0x72, 0x64, 0x50, 0x61,
	0x72, 0x74, 0x79, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x42, 0x1f, 0x5a, 0x1d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x70, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x7a, 0x68, 0x65, 0x6e, 0x67, 0x2f, 0x67, 0x61, 0x6d,
	0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_games_proto_rawDescOnce sync.Once
	file_games_proto_rawDescData = file_games_proto_rawDesc
)

func file_games_proto_rawDescGZIP() []byte {
	file_games_proto_rawDescOnce.Do(func() {
		file_games_proto_rawDescData = protoimpl.X.CompressGZIP(file_games_proto_rawDescData)
	})
	return file_games_proto_rawDescData
}

var file_games_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_games_proto_goTypes = []interface{}{
	(*RandomTicketRequest)(nil),                              // 0: games.RandomTicketRequest
	(*RandomTicketResponse)(nil),                             // 1: games.RandomTicketResponse
	(*AssignRandomIssuedTicketToThirdPartyUserRequest)(nil),  // 2: games.AssignRandomIssuedTicketToThirdPartyUserRequest
	(*AssignRandomIssuedTicketToThirdPartyUserResponse)(nil), // 3: games.AssignRandomIssuedTicketToThirdPartyUserResponse
}
var file_games_proto_depIdxs = []int32{
	0, // 0: games.Greeter.RandomTicket:input_type -> games.RandomTicketRequest
	2, // 1: games.Greeter.AssignRandomIssuedTicketToThirdPartyUser:input_type -> games.AssignRandomIssuedTicketToThirdPartyUserRequest
	1, // 2: games.Greeter.RandomTicket:output_type -> games.RandomTicketResponse
	3, // 3: games.Greeter.AssignRandomIssuedTicketToThirdPartyUser:output_type -> games.AssignRandomIssuedTicketToThirdPartyUserResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_games_proto_init() }
func file_games_proto_init() {
	if File_games_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_games_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RandomTicketRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_games_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RandomTicketResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_games_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AssignRandomIssuedTicketToThirdPartyUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_games_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AssignRandomIssuedTicketToThirdPartyUserResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_games_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_games_proto_goTypes,
		DependencyIndexes: file_games_proto_depIdxs,
		MessageInfos:      file_games_proto_msgTypes,
	}.Build()
	File_games_proto = out.File
	file_games_proto_rawDesc = nil
	file_games_proto_goTypes = nil
	file_games_proto_depIdxs = nil
}
